services:
  jekyll:
    image: jekyll/jekyll:latest
    # command: jekyll clean
    command: jekyll serve --watch
    # command: jekyll serve --watch --incremental
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
